AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: センサーから得た値を処理する Lambda を管理

Parameters:
  SlackChannel:
    Type: String
  SlackHookUrl:
    Type: String
  SNSCo2AlarmTopic:
    Type: String

Resources:
  Co2MetricsNotifyFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/co2
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 5
      Environment:
        Variables:
          SLACK_CHANNEL: !Ref SlackChannel
          SLACK_HOOK_URL: !Ref SlackHookUrl
          IMAGE_BUCKET_NAME: !Ref ImageBucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ImageBucket
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricWidgetImage
              Resource:
                - "*"
      Events:
        SNSCo2Alarm:
          Type: SNS
          Properties:
            Topic: !Ref SNSCo2AlarmTopic

  Co2MetricsNotifyFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Co2MetricsNotifyFn}
      RetentionInDays: 14

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            Status: Enabled

Outputs:
  Co2MetricsNotifyFn:
    Value: !GetAtt Co2MetricsNotifyFn.Arn

  Co2MetricsNotifyFnIamRole:
    Value: !GetAtt Co2MetricsNotifyFnRole.Arn
